apiVersion: v1
kind: Service
metadata:
  name: nodeapp2
  labels:
    app: nodeapp2
    service: nodeapa2p
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 9000
  selector:
    app: nodeapp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp2
  labels:
    app: nodeapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp2
  template:
    metadata:
      labels:
        app: nodeapp2
    spec:
      containers:
      - name: nodeapp2
        image: gcr.io/anthos-demo-335406/nodeapp2:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9000
      imagePullSecrets:
        - name: gcr-key
